### PR TITLE
Platform options

### PR DESCRIPTION
**Pull request by dgrossen**
## Description

Support ios or android only platfroms for mobile extensions

## Motivation and Context

Prevent extension developers providing bogus repository information that is displayed in the mobile install instructions

## How Has This Been Tested?

npm linked to validator and packager
validated against the example schema provided in the test folder

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Do these changes need to be released within a particular timeframe?

No

## Do these changes need to be coordinated with changes in other repositories?

Reactor sandbox, validator, packager, and scaffolding tool should be updated to validate against the new schema

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by amadt** [comment]
Doesn't look like androidOnly is supported?

**Comment by dgrossen** [comment]
@amadt it is by virtue of the allPlatforms schemas `"minItems": 1`

**Comment by amadt** [comment]
You know my next question. Why then does ios have a specific section. I feel stupid.

**Comment by dgrossen** [comment]
@amadt ha ha. Because JSON schemas are stupid. It can only validate a list of items that have the same schema OR tuple validation where ordinal index of each item matters. So iOS cannot come first for `allPlatforms` (or how it's designed currently) unless I provide another schema :-(

**Pull request merged**
